spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
      -
        id: employee
        uri: lb://employee
        predicates:
        - Path=/v1/employees/**
      -
        id: department
        uri: lb://department
        predicates:
        - Path=/v1/departments/**
eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/

server:
  port: 9191

logging:
  level:
    org:
      springframework:
        cloud:
          gateway:
            handler:
              RoutePredicateHandlerMapping: DEBUG
