spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
      -
        id: employee
        uri: lb://employee
        predicates:
        - Path=/v1/employees/**
      -
        id: department
        uri: lb://department
        predicates:
        - Path=/v1/departments/**
      -
        id: organization
        uri: lb://organization
        predicates:
          - Path=/v1/organizations/**

eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/

server:
  port: 9191

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: %5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
  level:
    org:
      springframework:
        web: DEBUG
